### ISSUE TITLE
'stride' renumbers frames?

### ISSUE THREAD

**Issue by vdbedem** [getcontacts/getcontacts#36] opened 2018-06-14 19:04 UTC
I run getcontacts on a dcd file with 2,500 frames

```bash
get_dynamic_contacts.py --topology protein.prmtop --trajectory protein_traj_1.dcd --sele "protein and resid 151 to 153" --stride 25 --itypes vdw --output protein.tsv
```

Screen output of this command reads:
```bash
Processing protein_traj_1.dcd with 2500 total frames and stride 25, skipping first 0 frames
Finished computing contacts for fragment 1 (frames 100 to 103) in 5.021215 s
Finished computing contacts for fragment 0 (frames 0 to 3) in 5.474545 s
Finished computing contacts for fragment 4 (frames 400 to 403) in 5.252845 s
Finished computing contacts for fragment 3 (frames 300 to 303) in 5.917687 s
```

I would expect frames 0, 25, 50, 75 for fragment 0, not 0 to 3. The frames are numbered 0 to 3 in the output file protein.tsv too. 

Are the frames selected incorrectly, or are they merely renumbered? Either way, this needs a fix.

**Comment by RasmusFonseca** [comment] 2018-06-15 00:13
Try pulling again. It should be fixed and I've clarified the stdout a bit also

**Comment by RasmusFonseca** [comment] 2018-06-21 23:03
Ok I've tested a bit more and am fairly confident that this works as intended now.

**Closed by RasmusFonseca** 2018-06-21 23:03 UTC
